config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  devise_for :users

  resource :devolutions, only: :create
  resource :withdraws, only: :create

  resources :stations, only: :index
  resources :trips, only: :index

  resource :damage_reports, only: :create
  resource :billings, only: :create

  root to: 'stations#index'
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  has_one :station, dependent: :destroy
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
# frozen_string_literal: true

class Bike < ApplicationRecord
  belongs_to :station
  has_many :trips

  enum status: {
    available: 0,
    on_trip: 1,
    damaged: 2
  }
end

app/models/bill.rb
# frozen_string_literal: true

class Bill < ApplicationRecord
  belongs_to :user
end

app/models/station.rb
# frozen_string_literal: true

class Station < ApplicationRecord
  belongs_to :address
  has_many :trips
  has_many :bikes, dependent: :destroy

  enum status: {
    full: 0,
    empty: 1,
    spots_available: 2
  }

  def update_status
    if station_full?
      self.full!
    elsif bikes_on_station.zero?
      self.empty!
    else
      self.spots_available!
    end
  end

  def station_full?
    bikes_on_station == self.spots_number
  end

  def vacancy_number
    self.spots_number - bikes_on_station
  end

  def bikes_on_station
    damaged_bikes + available_bikes
  end

  def damaged_bikes
    @damaged_bikes ||= self.bikes.count(&:damaged?)
  end

  def available_bikes
    @available_bikes ||= self.bikes.count(&:available?)
  end

  def bikes_on_trip
    @bikes_on_trip ||= self.bikes.count(&:on_trip?)
  end
end

app/models/trip.rb
# frozen_string_literal: true

class Trip < ApplicationRecord
  belongs_to :bike
  belongs_to :user
  belongs_to :start_station, class_name: 'Station'
  belongs_to :finish_station, class_name: 'Station', optional: true

  scope :user_trips, -> (current_user) do
    where(user: current_user).order(finish_time: :desc).select do |trip|
       trip.finish_station.present? && trip.finish_time > Date.current.prev_month
    end
  end

  def self.start_trip(bike:, user:, start_station:)
    create!(
      bike: bike,
      user: user,
      start_time: Time.current,
      start_station: start_station
    )
  end

  def self.finish_trip(user:, finish_station:)
    where(user: user).last.update!(
      finish_time: Time.current,
      finish_station: finish_station
    )
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trips
  has_many :bills
  has_one :bike

  validates :due_date, inclusion: 1..31

  after_create { SendBillingNotificationWorker.perform_at(date, self.due_date, self.id) }

  private

  def date
    (Date.new(Date.current.year, Date.current.month, self.due_date) + 1.month).to_s
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end
end

app/controllers/damage_reports_controller.rb
# frozen_string_literal: true

class DamageReportsController < ApplicationController
  before_action :authenticate_user!

  def create
    bike = Bike.find(params[:bike_id])

    if bike.available?
      bike.damaged!
      redirect_to stations_url, notice: I18n.t('bikes.damage_notification.success') % { bike_id: bike.id }
    else
      redirect_to stations_url, alert: I18n.t('bikes.damage_notification.failed')
    end
  end
end

app/controllers/devolutions_controller.rb
# frozen_string_literal: true

class DevolutionsController < ApplicationController
  before_action :authenticate_user!

  def create
    if service.new(station: station, bike: bike, user: current_user).execute
      redirect_to stations_url, notice: I18n.t('trips.devolution.success') % { bike_id: bike.id, station_name: station.name }
    else
      redirect_to stations_url, alert: I18n.t('trips.devolution.failed')
    end
  end

  private

  def service
    service ||= DevolutionService
  end

  def station
    station ||= Station.find(params[:station_id])
  end

  def bike
    bike ||= Bike.find(params[:bike_id])
  end
end

app/controllers/stations_controller.rb
# frozen_string_literal: true

class StationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @stations = Station.all
  end
end

app/controllers/trips_controller.rb
# frozen_string_literal: true

class TripsController < ApplicationController
  before_action :authenticate_user!

  def index
    @trips = Trip.user_trips(current_user)

    @actual_bill_value = Pricing::BillingValueService.new(user: current_user, current_trips: @trips).execute
  end
end

app/controllers/withdraws_controller.rb
# frozen_string_literal: true

class WithdrawsController < ApplicationController
  before_action :authenticate_user!

  def create
    if service.new(station: station, bike: bike, user: current_user).execute
      redirect_to stations_url, notice: I18n.t('trips.withdraw.success') % { bike_id: bike.id }
    else
      redirect_to stations_url, alert: I18n.t('trips.withdraw.failed')
    end
  end

  private

  def service
    service ||= WithdrawService
  end

  def station
    station ||= Station.find(params[:station_id])
  end

  def bike
    bike ||= Bike.find(params[:bike_id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>BikeTipoVc</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
  <%= javascript_pack_tag 'main' %>
  <header class="main-header">
    <% if current_user %>
      <div class="home-path">
        <%= link_to "BikeTipoVc", stations_path, class: 'home-icon' %>
      </div>
      <div class="header-buttons">
        <div class="current-user-logout">
          <%= button_to "logout", destroy_user_session_path, method: :delete, class: 'btn-logout' %>
        </div>
        <% if !current_page?(edit_user_registration_path	)  %>
        <div class="edit-current-user">
          <%= button_to "edit", edit_user_registration_path	, method: :get, class: 'btn-edit-user' %>
        </div>
        <% end %>
        <% if !current_page?(trips_path)  %>
        <div class="current-user-trips">
          <%= button_to "trips", trips_path, method: :get, class: 'btn-trips' %>
        </div>
        <% end %>
        <div class="current-user">
          <%= current_user.name %>
        </div>
      </div>
    <% else %>
      <div class="home-path">
        <p class="home-icon">BikeTipoVc</p>
      </div>
    <% end %>
  </header>

  <div>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% elsif alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
  </div>
  <%= yield %>
</body>

</html>

app/views/stations/_devolution.html.erb
<%= button_to "Devolver para #{station.name}", devolutions_path, method: :post, params: { bike_id: current_user.bike.id, station_id: station.id } %>

app/views/stations/_withdraw.html.erb
<div class='bikes'>
  <% station.bikes.each do |bike| %>
    <div class='bike'>
      ID: <%= bike.id  %>
      <% if bike.status == 'damaged' %>
        <i class='material-icons damaged'>highlight_off</i>
      <% else %>
        <i class='material-icons available'>check_circle_outline</i>
      <% end %>
      <% if bike.status == 'available' %>
      <div class='withdraw_button'>
          <%= button_to 'Alugar', withdraws_path, method: :post, params: { bike_id: bike.id, station_id: station.id } %>
      </div>
      <div class="damage_report_button">
        <%= button_to 'Reportar Dano', damage_reports_path, method: :post, data: { confirm: 'Você tem certeza?' }, params: { bike_id: bike.id } %>
      </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/stations/index.html.erb
<div class='stations'>
  <% @stations.each do |station| %>
    <div class='station' id='<%= station.name.downcase.gsub(' ', '-') %>'>
      <div class='station_info'>
        <section class='station_name'>
          <%= station.name %> (spots: <%= station.spots_number %>)
        </section>
        <% if current_user.bike.nil? %>
          <section class='available_bikes'>
            Bikes disponíveis: <%= station.available_bikes %>
          </section>
          <section class='damaged_bikes'>
            Bikes com problemas: <%= station.damaged_bikes %>
          </section>
        <% end %>
        <section class='station_spots'>
          Vagas disponíveis: <%= station.vacancy_number %>
        </section>
      </div>
      <%= render current_user.bike.present? ? 'devolution' : 'withdraw', station: station %>
    </div>
  <% end %>
</div>

app/views/trips/index.html.erb
<div class='trips'>
  <h1 class='title'>Suas viagens</h1>
  <h3>Fatura atual: R$ <%= @actual_bill_value %></h3>
  <% @trips.each do |trip| %>
    <div class='trip'>
      <div class='trip-info'>
        <section class='start-time'>
          Origem: <b><%= trip.start_station.name %></b> (<%= trip.start_time.strftime('%d/%m/%Y %H:%M') %>)
        </section>
        <section class='finish-time'>
          Destino: <b><%= trip.finish_station.name %></b> (<%= trip.finish_time.strftime('%d/%m/%Y %H:%M') %>)
        </section>
        <section class='trip-cost'>
          Valor: <b>R$ <%= trip.cost %></b>
        </section>
      </div>
    </div>
  <% end %>
</div>